version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1522:1521"  # Map host 1522 â†’ container 1521
    environment:
      - ORACLE_PWD=admin123
    volumes:
      - oracle_data:/opt/oracle/oradata

  hotelbooking:
    build: .
    container_name: hotelbooking-app
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=hotel_app
      - SPRING_DATASOURCE_PASSWORD=hotel123

volumes:
  oracle_data:
